version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build Application
          command: ./mvnw clean package -DskipTests

  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: ./mvnw test

  deploy:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Heroku CLI
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Login to Heroku Container Registry
          command: echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
      - run:
          name: Build Docker Image
          command: docker build -t registry.heroku.com/heroku-kw/web .
      - run:
          name: Push Docker Image to Heroku
          command: docker push registry.heroku.com/heroku-kw/web
      - run:
          name: Release the App on Heroku
          command: heroku container:release web --app heroku-kw

workflows:
  ci_flow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - test:
          filters:
            branches:
              only: develop

  cicd_flow:
    jobs:
      - build:
          filters:
            branches:
              only: release
      - test:
          requires:
            - build
          filters:
            branches:
              only: release
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: release